/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DachasRouteImport } from './routes/dachas'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HotelsSlugRouteImport } from './routes/hotels.$slug'
import { Route as AuthenticatedOwnerRouteImport } from './routes/_authenticated/owner'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedOwnerIndexRouteImport } from './routes/_authenticated/owner.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedProfileSettingsRouteImport } from './routes/_authenticated/profile.settings'
import { Route as AuthenticatedProfileFavoritesRouteImport } from './routes/_authenticated/profile.favorites'
import { Route as AuthenticatedProfileBookingsRouteImport } from './routes/_authenticated/profile.bookings'
import { Route as AuthenticatedOwnerUsersRouteImport } from './routes/_authenticated/owner.users'
import { Route as AuthenticatedOwnerSettingsRouteImport } from './routes/_authenticated/owner.settings'
import { Route as AuthenticatedOwnerMessagesRouteImport } from './routes/_authenticated/owner.messages'
import { Route as AuthenticatedOwnerHotelsRouteImport } from './routes/_authenticated/owner.hotels'
import { Route as AuthenticatedOwnerBookingsRouteImport } from './routes/_authenticated/owner.bookings'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'
import { Route as AuthenticatedBookingIdPayRouteImport } from './routes/_authenticated/booking.$id.pay'
import { Route as AuthenticatedBookingIdConfirmedRouteImport } from './routes/_authenticated/booking.$id.confirmed'
import { Route as AuthenticatedAdminHotelsNewRouteImport } from './routes/_authenticated/admin.hotels.new'
import { Route as AuthenticatedAdminHotelsIdRouteImport } from './routes/_authenticated/admin.hotels.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DachasRoute = DachasRouteImport.update({
  id: '/dachas',
  path: '/dachas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsSlugRoute = HotelsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HotelsRoute,
} as any)
const AuthenticatedOwnerRoute = AuthenticatedOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOwnerIndexRoute = AuthenticatedOwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedProfileSettingsRoute =
  AuthenticatedProfileSettingsRouteImport.update({
    id: '/profile/settings',
    path: '/profile/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileFavoritesRoute =
  AuthenticatedProfileFavoritesRouteImport.update({
    id: '/profile/favorites',
    path: '/profile/favorites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileBookingsRoute =
  AuthenticatedProfileBookingsRouteImport.update({
    id: '/profile/bookings',
    path: '/profile/bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOwnerUsersRoute = AuthenticatedOwnerUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedOwnerRoute,
} as any)
const AuthenticatedOwnerSettingsRoute =
  AuthenticatedOwnerSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerMessagesRoute =
  AuthenticatedOwnerMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerHotelsRoute =
  AuthenticatedOwnerHotelsRouteImport.update({
    id: '/hotels',
    path: '/hotels',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedOwnerBookingsRoute =
  AuthenticatedOwnerBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedOwnerRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedBookingIdPayRoute =
  AuthenticatedBookingIdPayRouteImport.update({
    id: '/booking/$id/pay',
    path: '/booking/$id/pay',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBookingIdConfirmedRoute =
  AuthenticatedBookingIdConfirmedRouteImport.update({
    id: '/booking/$id/confirmed',
    path: '/booking/$id/confirmed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHotelsNewRoute =
  AuthenticatedAdminHotelsNewRouteImport.update({
    id: '/hotels/new',
    path: '/hotels/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHotelsIdRoute =
  AuthenticatedAdminHotelsIdRouteImport.update({
    id: '/hotels/$id',
    path: '/hotels/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dachas': typeof DachasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/hotels/$slug': typeof HotelsSlugRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/owner/bookings': typeof AuthenticatedOwnerBookingsRoute
  '/owner/hotels': typeof AuthenticatedOwnerHotelsRoute
  '/owner/messages': typeof AuthenticatedOwnerMessagesRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/users': typeof AuthenticatedOwnerUsersRoute
  '/profile/bookings': typeof AuthenticatedProfileBookingsRoute
  '/profile/favorites': typeof AuthenticatedProfileFavoritesRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/owner/': typeof AuthenticatedOwnerIndexRoute
  '/admin/hotels/$id': typeof AuthenticatedAdminHotelsIdRoute
  '/admin/hotels/new': typeof AuthenticatedAdminHotelsNewRoute
  '/booking/$id/confirmed': typeof AuthenticatedBookingIdConfirmedRoute
  '/booking/$id/pay': typeof AuthenticatedBookingIdPayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dachas': typeof DachasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hotels/$slug': typeof HotelsSlugRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/owner/bookings': typeof AuthenticatedOwnerBookingsRoute
  '/owner/hotels': typeof AuthenticatedOwnerHotelsRoute
  '/owner/messages': typeof AuthenticatedOwnerMessagesRoute
  '/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/owner/users': typeof AuthenticatedOwnerUsersRoute
  '/profile/bookings': typeof AuthenticatedProfileBookingsRoute
  '/profile/favorites': typeof AuthenticatedProfileFavoritesRoute
  '/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/owner': typeof AuthenticatedOwnerIndexRoute
  '/admin/hotels/$id': typeof AuthenticatedAdminHotelsIdRoute
  '/admin/hotels/new': typeof AuthenticatedAdminHotelsNewRoute
  '/booking/$id/confirmed': typeof AuthenticatedBookingIdConfirmedRoute
  '/booking/$id/pay': typeof AuthenticatedBookingIdPayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dachas': typeof DachasRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hotels': typeof HotelsRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/owner': typeof AuthenticatedOwnerRouteWithChildren
  '/hotels/$slug': typeof HotelsSlugRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/owner/bookings': typeof AuthenticatedOwnerBookingsRoute
  '/_authenticated/owner/hotels': typeof AuthenticatedOwnerHotelsRoute
  '/_authenticated/owner/messages': typeof AuthenticatedOwnerMessagesRoute
  '/_authenticated/owner/settings': typeof AuthenticatedOwnerSettingsRoute
  '/_authenticated/owner/users': typeof AuthenticatedOwnerUsersRoute
  '/_authenticated/profile/bookings': typeof AuthenticatedProfileBookingsRoute
  '/_authenticated/profile/favorites': typeof AuthenticatedProfileFavoritesRoute
  '/_authenticated/profile/settings': typeof AuthenticatedProfileSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/owner/': typeof AuthenticatedOwnerIndexRoute
  '/_authenticated/admin/hotels/$id': typeof AuthenticatedAdminHotelsIdRoute
  '/_authenticated/admin/hotels/new': typeof AuthenticatedAdminHotelsNewRoute
  '/_authenticated/booking/$id/confirmed': typeof AuthenticatedBookingIdConfirmedRoute
  '/_authenticated/booking/$id/pay': typeof AuthenticatedBookingIdPayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dachas'
    | '/forgot-password'
    | '/hotels'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/owner'
    | '/hotels/$slug'
    | '/admin/bookings'
    | '/admin/settings'
    | '/owner/bookings'
    | '/owner/hotels'
    | '/owner/messages'
    | '/owner/settings'
    | '/owner/users'
    | '/profile/bookings'
    | '/profile/favorites'
    | '/profile/settings'
    | '/admin/'
    | '/owner/'
    | '/admin/hotels/$id'
    | '/admin/hotels/new'
    | '/booking/$id/confirmed'
    | '/booking/$id/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dachas'
    | '/forgot-password'
    | '/hotels'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/hotels/$slug'
    | '/admin/bookings'
    | '/admin/settings'
    | '/owner/bookings'
    | '/owner/hotels'
    | '/owner/messages'
    | '/owner/settings'
    | '/owner/users'
    | '/profile/bookings'
    | '/profile/favorites'
    | '/profile/settings'
    | '/admin'
    | '/owner'
    | '/admin/hotels/$id'
    | '/admin/hotels/new'
    | '/booking/$id/confirmed'
    | '/booking/$id/pay'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dachas'
    | '/forgot-password'
    | '/hotels'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/owner'
    | '/hotels/$slug'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/settings'
    | '/_authenticated/owner/bookings'
    | '/_authenticated/owner/hotels'
    | '/_authenticated/owner/messages'
    | '/_authenticated/owner/settings'
    | '/_authenticated/owner/users'
    | '/_authenticated/profile/bookings'
    | '/_authenticated/profile/favorites'
    | '/_authenticated/profile/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/owner/'
    | '/_authenticated/admin/hotels/$id'
    | '/_authenticated/admin/hotels/new'
    | '/_authenticated/booking/$id/confirmed'
    | '/_authenticated/booking/$id/pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DachasRoute: typeof DachasRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HotelsRoute: typeof HotelsRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dachas': {
      id: '/dachas'
      path: '/dachas'
      fullPath: '/dachas'
      preLoaderRoute: typeof DachasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$slug': {
      id: '/hotels/$slug'
      path: '/$slug'
      fullPath: '/hotels/$slug'
      preLoaderRoute: typeof HotelsSlugRouteImport
      parentRoute: typeof HotelsRoute
    }
    '/_authenticated/owner': {
      id: '/_authenticated/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AuthenticatedOwnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/': {
      id: '/_authenticated/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof AuthenticatedOwnerIndexRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/profile/settings': {
      id: '/_authenticated/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof AuthenticatedProfileSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/favorites': {
      id: '/_authenticated/profile/favorites'
      path: '/profile/favorites'
      fullPath: '/profile/favorites'
      preLoaderRoute: typeof AuthenticatedProfileFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/bookings': {
      id: '/_authenticated/profile/bookings'
      path: '/profile/bookings'
      fullPath: '/profile/bookings'
      preLoaderRoute: typeof AuthenticatedProfileBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/owner/users': {
      id: '/_authenticated/owner/users'
      path: '/users'
      fullPath: '/owner/users'
      preLoaderRoute: typeof AuthenticatedOwnerUsersRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/settings': {
      id: '/_authenticated/owner/settings'
      path: '/settings'
      fullPath: '/owner/settings'
      preLoaderRoute: typeof AuthenticatedOwnerSettingsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/messages': {
      id: '/_authenticated/owner/messages'
      path: '/messages'
      fullPath: '/owner/messages'
      preLoaderRoute: typeof AuthenticatedOwnerMessagesRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/hotels': {
      id: '/_authenticated/owner/hotels'
      path: '/hotels'
      fullPath: '/owner/hotels'
      preLoaderRoute: typeof AuthenticatedOwnerHotelsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/owner/bookings': {
      id: '/_authenticated/owner/bookings'
      path: '/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof AuthenticatedOwnerBookingsRouteImport
      parentRoute: typeof AuthenticatedOwnerRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/booking/$id/pay': {
      id: '/_authenticated/booking/$id/pay'
      path: '/booking/$id/pay'
      fullPath: '/booking/$id/pay'
      preLoaderRoute: typeof AuthenticatedBookingIdPayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/booking/$id/confirmed': {
      id: '/_authenticated/booking/$id/confirmed'
      path: '/booking/$id/confirmed'
      fullPath: '/booking/$id/confirmed'
      preLoaderRoute: typeof AuthenticatedBookingIdConfirmedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/hotels/new': {
      id: '/_authenticated/admin/hotels/new'
      path: '/hotels/new'
      fullPath: '/admin/hotels/new'
      preLoaderRoute: typeof AuthenticatedAdminHotelsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hotels/$id': {
      id: '/_authenticated/admin/hotels/$id'
      path: '/hotels/$id'
      fullPath: '/admin/hotels/$id'
      preLoaderRoute: typeof AuthenticatedAdminHotelsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminHotelsIdRoute: typeof AuthenticatedAdminHotelsIdRoute
  AuthenticatedAdminHotelsNewRoute: typeof AuthenticatedAdminHotelsNewRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminHotelsIdRoute: AuthenticatedAdminHotelsIdRoute,
  AuthenticatedAdminHotelsNewRoute: AuthenticatedAdminHotelsNewRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedOwnerRouteChildren {
  AuthenticatedOwnerBookingsRoute: typeof AuthenticatedOwnerBookingsRoute
  AuthenticatedOwnerHotelsRoute: typeof AuthenticatedOwnerHotelsRoute
  AuthenticatedOwnerMessagesRoute: typeof AuthenticatedOwnerMessagesRoute
  AuthenticatedOwnerSettingsRoute: typeof AuthenticatedOwnerSettingsRoute
  AuthenticatedOwnerUsersRoute: typeof AuthenticatedOwnerUsersRoute
  AuthenticatedOwnerIndexRoute: typeof AuthenticatedOwnerIndexRoute
}

const AuthenticatedOwnerRouteChildren: AuthenticatedOwnerRouteChildren = {
  AuthenticatedOwnerBookingsRoute: AuthenticatedOwnerBookingsRoute,
  AuthenticatedOwnerHotelsRoute: AuthenticatedOwnerHotelsRoute,
  AuthenticatedOwnerMessagesRoute: AuthenticatedOwnerMessagesRoute,
  AuthenticatedOwnerSettingsRoute: AuthenticatedOwnerSettingsRoute,
  AuthenticatedOwnerUsersRoute: AuthenticatedOwnerUsersRoute,
  AuthenticatedOwnerIndexRoute: AuthenticatedOwnerIndexRoute,
}

const AuthenticatedOwnerRouteWithChildren =
  AuthenticatedOwnerRoute._addFileChildren(AuthenticatedOwnerRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedOwnerRoute: typeof AuthenticatedOwnerRouteWithChildren
  AuthenticatedProfileBookingsRoute: typeof AuthenticatedProfileBookingsRoute
  AuthenticatedProfileFavoritesRoute: typeof AuthenticatedProfileFavoritesRoute
  AuthenticatedProfileSettingsRoute: typeof AuthenticatedProfileSettingsRoute
  AuthenticatedBookingIdConfirmedRoute: typeof AuthenticatedBookingIdConfirmedRoute
  AuthenticatedBookingIdPayRoute: typeof AuthenticatedBookingIdPayRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedOwnerRoute: AuthenticatedOwnerRouteWithChildren,
  AuthenticatedProfileBookingsRoute: AuthenticatedProfileBookingsRoute,
  AuthenticatedProfileFavoritesRoute: AuthenticatedProfileFavoritesRoute,
  AuthenticatedProfileSettingsRoute: AuthenticatedProfileSettingsRoute,
  AuthenticatedBookingIdConfirmedRoute: AuthenticatedBookingIdConfirmedRoute,
  AuthenticatedBookingIdPayRoute: AuthenticatedBookingIdPayRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface HotelsRouteChildren {
  HotelsSlugRoute: typeof HotelsSlugRoute
}

const HotelsRouteChildren: HotelsRouteChildren = {
  HotelsSlugRoute: HotelsSlugRoute,
}

const HotelsRouteWithChildren =
  HotelsRoute._addFileChildren(HotelsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DachasRoute: DachasRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HotelsRoute: HotelsRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
